CREATE VIEW dbo.vMemberAssociation AS 
SELECT MemberAssociationID,MemberID,AssociatedMemberID,ValMemberAssociationTypeID,ValRelationshipTypeID,EffectiveStartDateTime,EffectiveEndDateTime,LastUpdatedEmployeeID,InsertedDateTime,UpdatedDateTime
FROM MMS.dbo.MemberAssociation WITH(NOLOCK)
