
CREATE VIEW [dbo].[vMMSRevenueReportSummary]
AS
SELECT MMSRevenueReportSummaryID, 
       PostingClubName, 
       ItemAmount, 
       DepartmentID,
       DeptDescription, 
       ProductDescription, 
       MembershipClubname, 
       PostingClubID,
       DrawerActivityID, 
       PostDateTime, 
       TranDate, 
       TranTypeDescription,
       ValTranTypeID, 
       MemberID, 
       ItemSalesTax, 
       EmployeeID,
       PostingRegionDescription, 
       MemberFirstname, 
       MemberLastname,
       EmployeeFirstname, 
       EmployeeLastname, 
       ReasonCodeDescription, 
       TranItemID,
       TranMemberJoinDate, 
       MembershipID, 
       ProductID, 
       TranClubID, 
       Quantity,
       ItemDiscountAmount,
       DiscountAmount1,
       DiscountAmount2,
       DiscountAmount3,
       DiscountAmount4,
       DiscountAmount5,
       Discount1,
       Discount2,
       Discount3,
       Discount4,
       Discount5,
       LocalCurrencyCode
FROM   MMSRevenueReportSummary WITH (NOLOCK)
