CREATE VIEW dbo.vProductOnboardRuleSet AS 
SELECT ProductOnboardRuleSetID,ProductOnboardSetProductID,ProductOnboardRuleID,InsertedDateTime,UpdatedDateTime
FROM MMS.dbo.ProductOnboardRuleSet WITH(NOLOCK)
