CREATE VIEW dbo.vProgramNetworkEligibleMemberDate AS 
SELECT ProgramNetworkEligibleMemberDateID,ProgramNetworkEligibleMemberID,FromDateTime,ThruDateTime,InsertedDateTime,UpdatedDateTime
FROM MMS.dbo.ProgramNetworkEligibleMemberDate WITH(NOLOCK)
