CREATE VIEW dbo.vPTCreditCardUndeliverableTransaction AS 
SELECT PTCreditCardUndeliverableTransactionID,EntryDataSource,AccountNumber,ExpirationDate,TranAmount,ReferenceCode,TipAmount,EmployeeID,MemberID,CardHolderStreetAddress,CardHolderZipCode,TransactionDateTime,UTCTransactionDateTime,TransactionDateTimeZone,IndustryCode,ReasonMessage,CardType,PTCreditCardTerminalID,CardOnFileFlag,InsertedDateTime,MaskedAccountNumber,UpdatedDateTime,MaskedAccountNumber64,CardHolderName,TypeIndicator,ThirdPartyPOSPaymentID,HbcPaymentFlag
FROM MMS_Archive.dbo.PTCreditCardUndeliverableTransaction WITH(NOLOCK)
