

CREATE VIEW [dbo].[vReportDimDate] AS
SELECT DimDateKey,
       CalendarDate,
       FullDateDescription,
       DayOfWeekName,
       DayOfWeekAbbreviation,
       DayNumberInCalendarWeek,
       DayNumberInCalendarMonth,
       DayNumberInCalendarQuarter,
       DayNumberInCalendarYear,
       NumberOfDaysInMonth,
       WeekdayIndicator,
       LastDayInWeekIndicator,
       LastDayInMonthIndicator,
       CalendarWeekEndingDate,
       CalendarWeekNumberInYear,
       CalendarMonthName,
       CalendarMonthAbbreviation,
       CalendarNextMonthName,
       CalendarMonthNumberInYear,
       CalendarQuarterNumber,
       CalendarQuarterName,
       CalendarYear,
       PriorYearDate,
       PriorYearDayNumberInCalendarWeek,
       PriorYearDayNumberInCalendarMonth,
       PriorYearDayNumberInCalendarQuarter,
       PriorYearDayNumberInCalendarYear,
       PriorYearCalendarWeekNumberInYear,
       PriorYearCalendarYear,
       CalendarMonthStartingDate,
       CalendarPriorMonthStartingDate,
       CalendarNextMonthStartingDate,
       CalendarMonthEndingDate,
       CalendarPriorMonthEndingDate,
       CalendarNextMonthEndingDate,
       MonthStartingDimDateKey,
       PriorMonthStartingDimDateKey,
       NextMonthStartingDimDateKey,
       MonthEndingDimDateKey,
       PriorMonthEndingDimDateKey,
       NextMonthEndingDimDateKey,
       FullDateNumericDescription,
       YearMonthDescription,
       NumberOfDaysInMonthForDSSR,
       DayNumberInCalendarMonthForDSSR,
	   PayPeriodCode,
	   PayPeriodInMonth,
	   PayPeriodFullDescription,
	   PayPeriodFirstDayFlag,
	   PayPeriodLastDayFlag,
       FourDigitYearDashTwoDigitMonth,
	   NextDayDimDateKey,
       PeriodCode,
       StandardDateDescription,
       PriorDayDimDateKey,
       MonthDescriptionYear,
       FourDigitYearTwoDigitMonthTwoDigitDay,
       InsertedDateTime,
       InsertUser,
       BatchID
  FROM ReportDimDate
    WITH (NOLOCK)

