CREATE VIEW dbo.vSubsidyCompanyReimbursementProgram AS 
SELECT SubsidyCompanyReimbursementProgramID,SubsidyCompanyID,ReimbursementProgramID,Description,SendQualificationDataFlag,LTFCalcFlag,BatchNumber,MaximumReimbursement,EffectiveFromDateTime,EffectiveThruDateTime,InsertedDateTime,UpdatedDateTime,LTMatchMinEnrollment,MinEnrollmentMetFlag,DuesFloor,DisplayInOMSFlag,EligibilityRequirements,SubsidyOverrideDescription
FROM MMS.dbo.SubsidyCompanyReimbursementProgram WITH(NOLOCK)
