CREATE VIEW dbo.vValTerminationReason AS 
SELECT ValTerminationReasonID,Description,SortOrder,InsertedDateTime,UpdatedDateTime,DisplayUIFlag,AdditionalReasonDisplayUIFlag
FROM MMS.dbo.ValTerminationReason WITH(NOLOCK)
