CREATE VIEW dbo.vValProgramIdentifierValidationClass AS 
SELECT ValProgramIdentifierValidationClassID,Description,Class,SortOrder,InsertedDateTime,UpdatedDateTime
FROM MMS.dbo.ValProgramIdentifierValidationClass WITH(NOLOCK)
