CREATE TABLE [dbo].[ReportDimProduct] (
    [MMSProductID]                                          INT             NOT NULL,
    [ProductDescription]                                    VARCHAR (50)    NULL,
    [SalesCategoryDescription]                              VARCHAR (50)    NULL,
    [MMSDepartmentDescription]                              VARCHAR (50)    NULL,
    [SalesQuantityFactor]                                   INT             NULL,
    [MembershipGroupDescription]                            VARCHAR (50)    NULL,
    [FamilyStatusDescription]                               VARCHAR (50)    NULL,
    [MembershipTypeShortTermFlag]                           CHAR (1)        NULL,
    [MembershipTypeEmployeeFlag]                            CHAR (1)        NULL,
    [MembershipTypeInvestorFlag]                            CHAR (1)        NULL,
    [MembershipTypeTradeOutFlag]                            CHAR (1)        NULL,
    [MembershipTypeHouseAccountFlag]                        CHAR (1)        NULL,
    [MembershipTypeStudentFlexFlag]                         CHAR (1)        NULL,
    [MembershipType26AndUnderFlag]                          CHAR (1)        NULL,
    [MembershipTypeVIPFlag]                                 CHAR (1)        NULL,
    [MembershipTypeNonAccessFlag]                           CHAR (1)        NULL,
    [MembershipTypePendingNonAccessFlag]                    CHAR (1)        NULL,
    [MembershipTypeCorporateFlexFlag]                       CHAR (1)        NULL,
    [PayrollExtractTrackSalesFlag]                          CHAR (1)        NOT NULL,
    [PayrollExtractTrackServiceFlag]                        CHAR (1)        NOT NULL,
    [PayrollExtractStandardProductGroupFlag]                CHAR (1)        NOT NULL,
    [PayrollExtractMyLTBucksProductGroupFlag]               CHAR (1)        NOT NULL,
    [PayrollExtractName]                                    VARCHAR (50)    NOT NULL,
    [PayrollExtractRegionType]                              VARCHAR (50)    NOT NULL,
    [PayrollExtractStandardProductGroupName]                VARCHAR (50)    NOT NULL,
    [PayrollExtractExportStandardSalesAmountFlag]           CHAR (1)        NOT NULL,
    [PayrollExtractExportStandardServiceAmountFlag]         CHAR (1)        NOT NULL,
    [PayrollExtractExportStandardServiceQuantityFlag]       CHAR (1)        NOT NULL,
    [PayrollExtractExportStandardSortOrder]                 INT             NULL,
    [PayrollExtractMyLTBucksProductGroupName]               VARCHAR (50)    NOT NULL,
    [PayrollExtractExportMyLTBucksSalesAmountFlag]          CHAR (1)        NOT NULL,
    [PayrollExtractExportMyLTBucksServiceAmountFlag]        CHAR (1)        NOT NULL,
    [PayrollExtractExportMyLTBucksServiceQuantityFlag]      CHAR (1)        NOT NULL,
    [PayrollExtractExportMyLTBucksSortOrder]                INT             NULL,
    [MembershipTypeMyHealthCheckFlag]                       CHAR (1)        NULL,
    [MembershipTypeFlexiblePassFlag]                        CHAR (1)        NULL,
    [ProductGLAccount]                                      VARCHAR (10)    NOT NULL,
    [ProductGLDepartmentCode]                               VARCHAR (10)    NOT NULL,
    [ProductGLProductCode]                                  VARCHAR (10)    NOT NULL,
    [ProductRefundGLAccount]                                VARCHAR (10)    NOT NULL,
    [ProductDiscountGLAccount]                              VARCHAR (10)    NOT NULL,
    [MMSProductDisplayUIFlag]                               CHAR (1)        NULL,
    [MMSProductGLOverrideClubID]                            INT             NULL,
    [MMSRecurrentProductTypeDescription]                    VARCHAR (50)    NOT NULL,
    [MMSPackageProductFlag]                                 CHAR (1)        NULL,
    [MMSProductTipAllowedFlag]                              CHAR (1)        NULL,
    [ProductStatus]                                         VARCHAR (50)    NOT NULL,
    [RevenueReportingDepartmentName]                        VARCHAR (50)    NOT NULL,
    [RevenueProductGroupName]                               VARCHAR (50)    NOT NULL,
    [RevenueProductGroupSortOrder]                          INT             NULL,
    [RevenueProductGroupGLAccount]                          VARCHAR (10)    NOT NULL,
    [RevenueProductGroupGLDepartmentCode]                   VARCHAR (10)    NULL,
    [RevenueProductGroupGLProductCode]                      VARCHAR (10)    NULL,
    [RevenueProductGroupRefundGLAccount]                    VARCHAR (10)    NOT NULL,
    [RevenueProductGroupDiscountGLAccount]                  VARCHAR (10)    NOT NULL,
    [RevenueAllocationRuleName]                             VARCHAR (50)    NOT NULL,
    [MembershipTypeCheckInGroupLevel]                       INT             NULL,
    [MembershipTypeCheckInGroupDescription]                 VARCHAR (50)    NULL,
    [MembershipTypeEnrollmentTypeDescription]               VARCHAR (50)    NULL,
    [MembershipTypeAssessDuesFlag]                          CHAR (1)        NULL,
    [MembershipTypeAssessJuniorMemberDuesFlag]              CHAR (1)        NULL,
    [MembershipTypeWaiveAdminFeeFlag]                       CHAR (1)        NULL,
    [RevenueReportingRegionType]                            VARCHAR (50)    NOT NULL,
    [MembershipTypeGroupDescription]                        VARCHAR (255)   NULL,
    [JuniorMemberDuesFlag]                                  CHAR (1)        NOT NULL,
    [MembershipTypeFoundersFlag]                            CHAR (1)        NULL,
    [InsertedDateTime]                                      DATETIME        DEFAULT (getdate()) NOT NULL,
    [InsertUser]                                            VARCHAR (50)    DEFAULT (suser_sname()) NOT NULL,
    [BatchID]                                               INT             NOT NULL,
    [MMSPackageProductCountAsHalfSessionFlag]               CHAR (1)        NOT NULL,
    [ReportMTDAverageDeliveredSessionPriceFlag]             CHAR (1)        NOT NULL,
    [ReportMTDAverageSalePriceFlag]                         CHAR (1)        NOT NULL,
    [ReportConnectivityLeadGeneratorFlag]                   CHAR (1)        NOT NULL,
    [ReportNewBusinessOldBusinessFlag]                      CHAR (1)        NOT NULL,
    [PackageProductSessionTypeDimDescriptionKey]            INT             NOT NULL,
    [MembershipTypeDSSRGroupDescription]                    VARCHAR (50)    NULL,
    [MembershipTypeMembershipStatusSummaryGroupDescription] VARCHAR (100)   NULL,
    [ReportConnectivityPrimaryLeadGeneratorFlag]            CHAR (1)        NOT NULL,
    [ReportDepartmentalDSSRFlag]                            CHAR (1)        NOT NULL,
    [CorporateTransferFlag]                                 CHAR (1)        NOT NULL,
    [CorporateTransferMultiplier]                           NUMERIC (12, 2) NOT NULL,
    [DSSRIFAdminFeeFlag]                                    CHAR (1)        NOT NULL,
    [DSSRDowngradeOtherEnrollmentFeeFlag]                   CHAR (1)        NOT NULL,
    [ExperienceLifeMagazineFlag]                            CHAR (1)        NOT NULL,
    [DimReportingHierarchyKey]                              INT             NOT NULL,
    [WorkdayAccount]                                        VARCHAR (6)     NOT NULL,
    [WorkdayCostCenter]                                     VARCHAR (6)     NOT NULL,
    [WorkdayOffering]                                       VARCHAR (10)    NOT NULL,
    [WorkdayOverRideRegion]                                 VARCHAR (4)     NOT NULL,
    [WorkdayRevenueProductGroupAccount]                     VARCHAR (6)     NOT NULL,
    [DeferredRevenueFlag]                                   CHAR (1)        NOT NULL,
    [WorkdayRefundGLAccount]                                VARCHAR (10)    NOT NULL,
    [WorkdayDiscountGLAccount]                              VARCHAR (10)    NOT NULL,
    [WorkdayRevenueProductGroupRefundGLAccount]             VARCHAR (10)    NOT NULL,
    [WorkdayRevenueProductGroupDiscountGLAccount]           VARCHAR (10)    NOT NULL,
    [MembershipTypeLifeTimeHealthFlag]                      CHAR (1)        NULL,
    CONSTRAINT [PK_MMSProductID] PRIMARY KEY CLUSTERED ([MMSProductID] ASC) WITH (FILLFACTOR = 100),
    CHECK ([MembershipTypeLifeTimeHealthFlag]='N' OR [MembershipTypeLifeTimeHealthFlag]='Y'),
    CONSTRAINT [CHECK_ReportDimProduct_MMSPackageProductCountAsHalfSessionFlag] CHECK ([MMSPackageProductCountAsHalfSessionFlag]='N' OR [MMSPackageProductCountAsHalfSessionFlag]='Y'),
    CONSTRAINT [CK_ReportDimProduct_ReportConnectivityLeadGeneratorFlag] CHECK ([ReportConnectivityLeadGeneratorFlag]='N' OR [ReportConnectivityLeadGeneratorFlag]='Y'),
    CONSTRAINT [CK_ReportDimProduct_ReportMTDAverageDeliveredSessionPriceFlag] CHECK ([ReportMTDAverageDeliveredSessionPriceFlag]='N' OR [ReportMTDAverageDeliveredSessionPriceFlag]='Y'),
    CONSTRAINT [CK_ReportDimProduct_ReportMTDAverageSalePriceFlag] CHECK ([ReportMTDAverageSalePriceFlag]='N' OR [ReportMTDAverageSalePriceFlag]='Y'),
    CONSTRAINT [CK_ReportDimProduct_ReportNewBusinessOldBusinessFlag] CHECK ([ReportNewBusinessOldBusinessFlag]='N' OR [ReportNewBusinessOldBusinessFlag]='Y')
);

