CREATE TABLE [dbo].[zzzECommMembers] (
    [Customer ID]                    NVARCHAR (50)  NULL,
    [Employee#]                      NVARCHAR (50)  NULL,
    [Member#]                        NVARCHAR (50)  NULL,
    [Name]                           NVARCHAR (50)  NULL,
    [Street1]                        NVARCHAR (200) NULL,
    [Street2]                        NVARCHAR (200) NULL,
    [City]                           NVARCHAR (50)  NULL,
    [State]                          NVARCHAR (50)  NULL,
    [Zip]                            NVARCHAR (50)  NULL,
    [SV Default BillingAddress ID]   NVARCHAR (50)  NULL,
    [SV Default Shipping Address ID] NVARCHAR (50)  NULL,
    [Email]                          NVARCHAR (50)  NULL,
    [Cust-Billto ID]                 NVARCHAR (50)  NULL,
    [Cust-Shipto ID]                 NVARCHAR (50)  NULL,
    [Default BillingAddress ID]      NVARCHAR (50)  NULL,
    [Default Billing Addr1]          NVARCHAR (200) NULL,
    [Default Billing Addr2]          NVARCHAR (200) NULL,
    [Default Billing City]           NVARCHAR (50)  NULL,
    [Default Billing State]          NVARCHAR (50)  NULL,
    [Default Billing Zip]            NVARCHAR (50)  NULL,
    [Profile Same as Billing ]       NVARCHAR (50)  NULL,
    [Default Shipping Address ID]    NVARCHAR (50)  NULL,
    [Default Shipping Addr1]         NVARCHAR (200) NULL,
    [Default Shipping Addr2]         NVARCHAR (200) NULL,
    [Default Shipping City]          NVARCHAR (50)  NULL,
    [Default Shipping State]         NVARCHAR (50)  NULL,
    [Default Shipping Zip]           NVARCHAR (50)  NULL,
    [Profile Same as Shipping]       NVARCHAR (50)  NULL
);

