

--THIS PROCEDURE RETUNRS THE DETAILS OF MEMBERSHIP SOLD
--FOR MONTH TO DAY TILL YESTERDAY FOR All CLUBS.

CREATE PROCEDURE mmsClosedMembershipsAllClubs
AS
BEGIN

  SET XACT_ABORT ON
  SET NOCOUNT ON
  EXEC mmsClosedMemberships ''
END



